### ISSUE TITLE
按照流程操作在启用  Workflows 后运行异常

### ISSUE THREAD

**Issue by Heart-Beats** [TeaTools/auto-sync-blog#7]
报错信息如下：
```
Run npm install
  npm install
  npm run build
  shell: /usr/bin/bash -e {0}

added 1 package, and audited 1463 packages in 3s

110 packages are looking for funding
  run `npm fund` for details

43 vulnerabilities (1 low, 13 moderate, [2](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:2)2 high, 7 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> build
> vuepress build docs

wait Extracting site metadata...
tip Apply theme vuepress-theme-reco ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress-reco/back-to-top (i.e. "@vuepress-reco/vuepress-plugin-back-to-top") ...
tip Apply plugin @vuepress-reco/pagation (i.e. "@vuepress-reco/vuepress-plugin-pagation") ...
tip Apply plugin @vuepress-reco/comments (i.e. "@vuepress-reco/vuepress-plugin-comments") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/blog (i.e. "@vuepress/plugin-blog") ...
tip Apply plugin smooth-scroll (i.e. "vuepress-plugin-smooth-scroll") ...
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
[success] [webpackbar] Server: Compiled successfully in 17.69s
[success] [webpackbar] Client: Compiled successfully in 17.78s
wait Rendering static HTML...
[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"

found in

---> <NavLink>
       <NavLinks>
         <Navbar>
           <Common>
             <Tags>
               <GlobalLayout>
                 <Root>
[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"

found in

---> <NavLink>
       <NavLinks>
         <Navbar>
           <Common>
             <Anonymous>
               <GlobalLayout>
                 <Root>
[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"

found in

---> <NavLink>
       <NavLinks>
         <Navbar>
           <Common>
             <TimeLine>
               <GlobalLayout>
                 <Root>
[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"

found in

---> <NavLink>
       <NavLinks>
         <Navbar>
           <Common>
             <Category>
               <GlobalLayout>
                 <Root>
error Error rendering /tag/: false
undefined
error Error rendering /timeline/: false
undefined
error Error rendering /categories/专栏/: false
undefined
[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"

found in

---> <NavLink>
       <NavLinks>
         <Navbar>
           <Common>
             <Anonymous>
               <GlobalLayout>
                 <Root>
[Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"

found in

---> <NavLink>
       <NavLinks>
         <Navbar>
           <Common>
             <Anonymous>
               <GlobalLayout>
                 <Root>
error Error rendering /categories/: false
undefined
error Error rendering /: false
undefined
error Error rendering /sort/column/我的专栏.html: false
undefined
TypeError: Cannot read properties of undefined (reading 'match')
    at ensureExt (node_modules/vuepress-theme-reco/helpers/utils.js:[3](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:3)5:25)
    at 0.server-bundle.js:1683:92
    at Object.get value [as value] (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue/dist/vue.runtime.common.dev.js:1335:2[4](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:4))
    at Proxy.get (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue/dist/vue.runtime.common.dev.js:1140:28)
    at Proxy.render (node_modules/vuepress-theme-reco/components/NavLink.vue:1:117)
    at VueComponent.Vue._render (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue/dist/vue.runtime.common.dev.js:2[5](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:6)90:28)
    at resolve (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7221:33)
    at waitForServerPrefetch (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7105:5)
    at renderComponentInner (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7235:5)
    at renderComponent (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7195:9)
    at RenderContext.renderNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7112:9)
    at RenderContext.next (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3[6](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:7)[7](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:8)2:37)
    at cachedWrite (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3547:17)
    at renderStringNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7311:[9](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:10))
    at RenderContext.renderNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7[10](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:11)9:9)
    at RenderContext.next (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3672:37)
    at RenderContext.cachedWrite [as write] (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3547:17)
    at RenderContext.next (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3677:41)
    at RenderContext.cachedWrite [as write] (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3547:17)
    at RenderContext.next (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3677:41)
    at RenderContext.cachedWrite [as write] (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3547:17)
    at RenderContext.renderNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7127:17)
    at RenderContext.next (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3672:37)
    at cachedWrite (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3547:17)
    at renderElement (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7332:9)
    at renderNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7[11](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:12)5:9)
    at resolve (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7232:9)
    at waitForServerPrefetch (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7105:5)
    at renderComponentInner (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7235:5)
    at renderComponent (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7195:9)
    at RenderContext.renderNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:71[12](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:13):9)
    at RenderContext.next (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3672:37)
    at cachedWrite (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3547:17)
    at renderElement (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7343:9)
    at renderNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:71[15](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:16):9)
    at resolve (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7232:9)
    at waitForServerPrefetch (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7105:5)
    at renderComponentInner (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7235:5)
    at renderComponent (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7195:9)
    at renderNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7112:9)
    at resolve (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7232:9)
    at waitForServerPrefetch (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7105:5)
    at renderComponentInner (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7235:5)
    at renderComponent (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7195:9)
    at RenderContext.renderNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7112:9)
    at RenderContext.next (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3672:37)
    at cachedWrite (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:3547:[17](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:18))
    at renderStringNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7[31](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:32)1:9)
    at RenderContext.renderNode (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:7109:9)
    at RenderContext.next (/home/runner/work/auto-sync-blog/auto-sync-blog/node_modules/vue-server-renderer/build.dev.js:[36](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:37)72:[37](https://github.com/Heart-Beats/auto-sync-blog/actions/runs/4761829387/jobs/8463430734#step:6:38))
Error: Process completed with exit code 1.
```

**Comment by NanFangZhe404** [comment]
很高兴能ti替你解答；这里应该是文件没有生成问题，你试一下在掘金那边写一篇文章，然后再进行操作；或者检查一下第三步
![image](https://user-images.githubusercontent.com/86654383/233623357-d7580a6d-b1c7-431c-b6ad-4a9e877afd40.png)

**Comment by Heart-Beats** [comment]
> 很高兴能ti替你解答；这里应该是文件没有生成问题，你试一下在掘金那边写一篇文章，然后再进行操作；

目前由于账号原因无法在掘金发布文章，因为掘金发布需要绑定手机号，我手机号现在是绑定了另一个账号，还没注销成功。这个不可以做个兼容处理吗？

**Comment by NanFangZhe404** [comment]
不，这个有兼容（我本地使用启动你的没问题），你这个个例，不知道差了哪一步，还有帐号问题无法发文章这个，我也不清楚呢，我只是用到掘金用户id。: )
有详细视频教程地址了。
https://www.bilibili.com/video/BV1Vh4y1p7dq/
